[package]
name = "nqueens"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
rayon = "1.10"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
